### ISSUE TITLE
Flights order

### ISSUE THREAD

**Issue by dimoniet** [vsimakhin/web-logbook-mobile#11]
Flights entered via de app are not sorted correctly, see last flight from attached image.

![Imagen de WhatsApp 2023-08-04 a las 20 57 55](https://github.com/vsimakhin/web-logbook-mobile/assets/1335194/fe6db1db-02bb-41d6-982e-6910086e66b7)

**Comment by vsimakhin** [comment]
thanks! will check it

**Comment by vsimakhin** [comment]
I've added a fix and will release once I fix few issues for the main app
